# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0004_siteuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='zip_zode',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
