# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0006_auto_20180121_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='zip_zode',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
