# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0007_auto_20180121_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='activation_key2',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
