# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0008_siteuser_activation_key2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='zip_zode',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='zipper',
            field=models.CharField(default=1, max_length=5),
        ),
    ]
