# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0009_auto_20180121_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_no', models.CharField(blank=True, max_length=5, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('zip_class', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zip_codes',
            },
        ),
    ]
