# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newscontent', '0010_zipcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcodes',
            name='id',
        ),
        migrations.AlterField(
            model_name='zipcodes',
            name='rec_no',
            field=models.CharField(blank=True, default='0', max_length=5, primary_key=True, serialize=False),
        ),
    ]
